### ISSUE TITLE
存在刷物品BUG

### ISSUE THREAD

**Issue by L-fanhua** [shuangshun/Hat#1]
当头上戴着物品时 再输入!!hat 会把手上的物品戴在头上 但不会清除手上的物品
![QQ20240828-144238](https://github.com/user-attachments/assets/2b919d51-dcca-40c4-80d7-9d1dc3c3fdc2)
服务器版本 1.21
hat版本 1.0.1

**Comment by shuangshun** [comment]
> 当头上戴着物品时 再输入!!hat 会把手上的物品戴在头上 但不会清除手上的物品 ![QQ20240828-144238](https://private-user-images.githubusercontent.com/98416104/362164505-2b919d51-dcca-40c4-80d7-9d1dc3c3fdc2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NDQyODgsIm5iZiI6MTcyNDg0Mzk4OCwicGF0aCI6Ii85ODQxNjEwNC8zNjIxNjQ1MDUtMmI5MTlkNTEtZGNjYS00MGM0LTgwZDctOWQxZGMzYzNmZGMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDExMTk0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU4NGNhMWE5NmIyOGZkZjNiZTU4MTE2ZTZjMzVjODEyNjQxNDExZjI1NDNmNGY0ZTI4NmMzYWFiNmQyODdiMWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jPTvXGspx1FmYXzwOzm24CwvYpIa33jT35osQftlP-w) 服务器版本 1.21 hat版本 1.0.1

本插件现并未兼容1.21以后的版本,因为从1.21开始,物品NBT改为了组件

**Comment by Seungmin922** [comment]
我发现了，但想复刻的时候不行

**Comment by shuangshun** [comment]
> 我发现了，但想复刻的时候不行

当头上已经有物品时,插件会采用另一种方式来交换物品,但是我只写了NBT的处理并未考虑组件
